### PR TITLE
Own handle function

### PR DESCRIPTION
**Pull request by Smip**
I added ability to use own handle function.

I use this feature for upload images to server.

```
   modules = {
      imageDrop: {
           handler: this.upload.bind(this)
      }
    };

  upload(file, callback){
    const fb = new FormData();
    fb.append('file', file, file.name);
    this.filesService.addFile(fb).subscribe(event => {
      callback(event['response']);
    });
  }
```

### CODE REVIEW

**Comment by ariefurtado** [comment]
Can u generate a rc with this ??? I really need it :D

**Comment by Smip** [comment]
@ariefurtado Sorry, what do you mean by rc?

**Comment by stargazing-dino** [comment]
@kensnyder Any reason this hasn't been merged? It'd really help me at the moment

**Comment by kensnyder** [comment]
@Nolence I'm closing this PR in favor of a slightly different one. See [PR #22](https://github.com/kensnyder/quill-image-drop-module/pull/22). Please review and let me know if it will work for you before I merge it.

**Pull request closed without merging**
